### ISSUE TITLE
TTransportException: Frame size large than max lenght

### ISSUE THREAD

**Issue by tibraga** [OpenTSDB/asynccassandra#11]
Hello,

I'm running OpenTSDB 2.3 with Cassandra, and when query the metrics with many points, occurs the below exception. I changed the properties of Cassandra Server and not works. How to fix it?

Properties Cassandra Server:
`thrift_framed_transport_size_in_mb: 60`

The Exception:
`Oct 25 16:52:04 opentsdb-qa2-01 tsdb: Caused by: org.apache.thrift.transport.TTransportException: Frame size (17572007) larger than max length (16384000)!
Oct 25 16:52:04 opentsdb-qa2-01 tsdb: at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:137) ~[asynccassandra-0.0.1-20160229.001338-4-jar-with-dependencies.jar:na]
Oct 25 16:52:04 opentsdb-qa2-01 tsdb: at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101) ~[asynccassandra-0.0.1-20160229.001338-4-jar-with-dependencies.jar:na]
Oct 25 16:52:04 opentsdb-qa2-01 tsdb: at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84) ~[asynccassandra-0.0.1-20160229.001338-4-jar-with-dependencies.jar:na]
Oct 25 16:52:04 opentsdb-qa2-01 tsdb: at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:362) ~[asynccassandra-0.0.1-20160229.001338-4-jar-with-dependencies.jar:na]
Oct 25 16:52:04 opentsdb-qa2-01 tsdb: at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:284) ~[asynccassandra-0.0.1-20160229.001338-4-jar-with-dependencies.jar:na]
Oct 25 16:52:04 opentsdb-qa2-01 tsdb: at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:191) ~[asynccassandra-0.0.1-20160229.001338-4-jar-with-dependencies.jar:na]
Oct 25 16:52:04 opentsdb-qa2-01 tsdb: at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69) ~[asynccassandra-0.0.1-20160229.001338-4-jar-with-dependencies.jar:na]
Oct 25 16:52:04 opentsdb-qa2-01 tsdb: at org.apache.cassandra.thrift.Cassandra$Client.recv_get_range_slices(Cassandra.java:811) ~[asynccassandra-0.0.1-20160229.001338-4-jar-with-dependencies.jar:na]
Oct 25 16:52:04 opentsdb-qa2-01 tsdb: at org.apache.cassandra.thrift.Cassandra$Client.get_range_slices(Cassandra.java:795) ~[asynccassandra-0.0.1-20160229.001338-4-jar-with-dependencies.jar:na]
Oct 25 16:52:04 opentsdb-qa2-01 tsdb: at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$2$1.internalExecute(ThriftColumnFamilyQueryImpl.java:413) ~[asynccassandra-0.0.1-20160229.001338-4-jar-with-dependencies.jar:na]
Oct 25 16:52:04 opentsdb-qa2-01 tsdb: at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$2$1.internalExecute(ThriftColumnFamilyQueryImpl.java:400) ~[asynccassandra-0.0.1-20160229.001338-4-jar-with-dependencies.jar:na]
Oct 25 16:52:04 opentsdb-qa2-01 tsdb: at com.netflix.astyanax.thrift.AbstractOperationImpl.execute(AbstractOperationImpl.java:60) ~[asynccassandra-0.0.1-20160229.001338-4-jar-with-dependencies.jar:na]
Oct 25 16:52:04 opentsdb-qa2-01 tsdb: ... 9 common frames omitted`

**Comment by pavanshetty05** [comment]
Hi Team 
     Is there any solution for this ? We are also facing  similar issue after integration with Cassandra 2.0.2.  As per my understanding in  source code need to increase the  threaft client  size while making call  to  Cassandra server .   This issue causes when they are retrieving a  huge data  from Cassandra   server .

**Comment by manolama** [comment]
@pavanshetty05 Will https://github.com/OpenTSDB/asynccassandra/pull/9 do what you need? If so I can clean it an merge it in.

**Comment by ros-tech-dev** [comment]
Hi @manolama @alienth  @pavanshetty05  , 

I am getting the same error while configuring OpenTSDB with cassandra backend.
Can you please let me know how to proceed from here. Any solution for this.

**Caused by: com.netflix.astyanax.connectionpool.exceptions.TransportException: TransportException: [host=x.x.x.x(x.x.x.x):9160, latency=4247(4247), attempts=1]org.apache.thrift.transport.TTransportException: Frame size (25382458) larger than max length (16384000)!**

Thanks
