### ISSUE TITLE
Config Cassendra DB

### ISSUE THREAD

**Issue by pavanshetty05** [OpenTSDB/asynccassandra#5]
Where to add the Cassandra Db connectivity details ? 
Present YML file have only asynccassandra.seeds where we are specifying  only port and IP address of the   Cassandra. Where to add the Cassendra DB user name and password details (Schema details)?

**Comment by pavanshetty05** [comment]
This is the exception what i am getting  
Caused by: InvalidRequestException(why:You have not logged in)
	at org.apache.cassandra.thrift.Cassandra$get_slice_result$get_slice_resultStandardScheme.read(Cassandra.java:11806)
	at org.apache.cassandra.thrift.Cassandra$get_slice_result$get_slice_resultStandardScheme.read(Cassandra.java:11773)
	at org.apache.cassandra.thrift.Cassandra$get_slice_result.read(Cassandra.java:11699)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_get_slice(Cassandra.java:671)
	at org.apache.cassandra.thrift.Cassandra$Client.get_slice(Cassandra.java:655)
	at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$1$2.internalExecute(ThriftColumnFamilyQueryImpl.java:201)
	at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$1$2.internalExecute(ThriftColumnFamilyQueryImpl.java:188)
	at com.netflix.astyanax.thrift.AbstractOperationImpl.execute(AbstractOperationImpl.java:60)

**Comment by manolama** [comment]
Ah, we don't have a parameter yet to pass in the user credentials. If you have time for a tiny PR it shouldn't be too hard to add.
